IMPORT DATASET

IMPORT LIBRARY

In [1]:
import numpy as np
import pandas as pd

READ DATASET AND PRE-PROCESSING

In [2]:
df = pd.read_csv('/content/spam.csv', encoding="ISO-8859-1")
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [3]:
df.tail()

v1                                                 v2 Unnamed: 2  \
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN

In [4]:
# Checking the datatype
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB


In [5]:
df.isnull().sum()

v1               0
v2               0
Unnamed: 2    5522
Unnamed: 3    5560
Unnamed: 4    5566
dtype: int64

In [17]:
#Taking the open column for training
train_set = df.iloc[:,1:2].values
train_set

array([['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'],
       ['Ok lar... Joking wif u oni...'],
       ["Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"],
       ...,
       ['Pity, * was in mood for that. So...any other suggestions?'],
       ["The guy did some bitching but I acted like i'd be interested in buying something else next week and he gave it to us for free"],
       ['Rofl. Its true to its name']], dtype=object)

In [18]:
# Scaling

from sklearn.preprocessing import LabelEncoder

sc = LabelEncoder()
scaled_tr = sc.fit_transform(train_set)
scaled_tr

array([1079, 3101, 1000, ..., 3286, 3901, 3409])

In [19]:
sc.inverse_transform([[1079]])

array(['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'],
      dtype=object)

In [20]:
scaled_tr[60-60:60-0]

array([1079, 3101, 1000, 4088, 2757, 1010,  915,  368, 4249, 1236, 2086,
       3437, 4145, 2154, 1684, 4590, 3013,  890,  967,  897, 2258, 2338,
       3604,  149,  959, 2382, 2593,  730, 2067,  157, 4262, 4655, 2437,
        975, 3821, 4954, 3232, 1927,  301, 1362, 3318,  718,   46, 4242,
       1167, 2804,  739,  951, 4656, 4086, 4462,  121, 2427, 4582, 3446,
        766,  602, 3671, 3773, 4744])

CREATE THE MODEL

In [21]:
# Split dependent and independent

x_train = []
y_train = []

for i in range(60,1258):
  x_train.append(scaled_tr[i-60:i-0])
  y_train.append(scaled_tr[i-0])

In [22]:
x_train

[array([1079, 3101, 1000, 4088, 2757, 1010,  915,  368, 4249, 1236, 2086,
        3437, 4145, 2154, 1684, 4590, 3013,  890,  967,  897, 2258, 2338,
        3604,  149,  959, 2382, 2593,  730, 2067,  157, 4262, 4655, 2437,
         975, 3821, 4954, 3232, 1927,  301, 1362, 3318,  718,   46, 4242,
        1167, 2804,  739,  951, 4656, 4086, 4462,  121, 2427, 4582, 3446,
         766,  602, 3671, 3773, 4744]),
 array([3101, 1000, 4088, 2757, 1010,  915,  368, 4249, 1236, 2086, 3437,
        4145, 2154, 1684, 4590, 3013,  890,  967,  897, 2258, 2338, 3604,
         149,  959, 2382, 2593,  730, 2067,  157, 4262, 4655, 2437,  975,
        3821, 4954, 3232, 1927,  301, 1362, 3318,  718,   46, 4242, 1167,
        2804,  739,  951, 4656, 4086, 4462,  121, 2427, 4582, 3446,  766,
         602, 3671, 3773, 4744, 4908]),
 array([1000, 4088, 2757, 1010,  915,  368, 4249, 1236, 2086, 3437, 4145,
        2154, 1684, 4590, 3013,  890,  967,  897, 2258, 2338, 3604,  149,
         959, 2382, 2593,  730, 

In [23]:
x_train,y_train = np.array(x_train),np.array(y_train)

In [24]:
x_train

array([[1079, 3101, 1000, ..., 3671, 3773, 4744],
       [3101, 1000, 4088, ..., 3773, 4744, 4908],
       [1000, 4088, 2757, ..., 4744, 4908, 1223],
       ...,
       [4830, 4431, 1318, ..., 4662, 2717, 4463],
       [4431, 1318,  204, ..., 2717, 4463, 2409],
       [1318,  204, 2754, ..., 4463, 2409, 2937]])

In [25]:
x_train.shape

(1198, 60)

In [26]:
x_train = np.reshape(x_train,(1198, 60, 1))
x_train.shape

(1198, 60, 1)

TEST THE MODEL

In [27]:
x_test = []
y_test = []

for i in range(60,1258):
  x_test.append(scaled_tr[i-60:i-0])
  y_test.append(scaled_tr[i-0])

In [28]:
x_test

[array([1079, 3101, 1000, 4088, 2757, 1010,  915,  368, 4249, 1236, 2086,
        3437, 4145, 2154, 1684, 4590, 3013,  890,  967,  897, 2258, 2338,
        3604,  149,  959, 2382, 2593,  730, 2067,  157, 4262, 4655, 2437,
         975, 3821, 4954, 3232, 1927,  301, 1362, 3318,  718,   46, 4242,
        1167, 2804,  739,  951, 4656, 4086, 4462,  121, 2427, 4582, 3446,
         766,  602, 3671, 3773, 4744]),
 array([3101, 1000, 4088, 2757, 1010,  915,  368, 4249, 1236, 2086, 3437,
        4145, 2154, 1684, 4590, 3013,  890,  967,  897, 2258, 2338, 3604,
         149,  959, 2382, 2593,  730, 2067,  157, 4262, 4655, 2437,  975,
        3821, 4954, 3232, 1927,  301, 1362, 3318,  718,   46, 4242, 1167,
        2804,  739,  951, 4656, 4086, 4462,  121, 2427, 4582, 3446,  766,
         602, 3671, 3773, 4744, 4908]),
 array([1000, 4088, 2757, 1010,  915,  368, 4249, 1236, 2086, 3437, 4145,
        2154, 1684, 4590, 3013,  890,  967,  897, 2258, 2338, 3604,  149,
         959, 2382, 2593,  730, 

ADDING LAYERS

In [29]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM

In [30]:
model = Sequential()
model.add(LSTM(50, input_shape = (60,1),return_sequences=True))
model.add(LSTM(50,return_sequences=True))
model.add(LSTM(50,return_sequences=True))
model.add(LSTM(50,return_sequences=True))
model.add(Dense(1))

COMPILE THE MODEL

In [31]:
model.compile(optimizer='adam',loss='mse')

FIT THE MODEL

In [32]:
model.fit(x_train, y_train, epochs=10, batch_size=32)

Epoch 1/10
38/38 [==============================] - 12s 115ms/step - loss: 9162873.0000
Epoch 2/10
38/38 [==============================] - 4s 113ms/step - loss: 9131528.0000
Epoch 3/10
38/38 [==============================] - 4s 113ms/step - loss: 9116357.0000
Epoch 4/10
38/38 [==============================] - 4s 115ms/step - loss: 9104269.0000
Epoch 5/10
38/38 [==============================] - 4s 114ms/step - loss: 9092916.0000
Epoch 6/10
38/38 [==============================] - 4s 114ms/step - loss: 9081905.0000
Epoch 7/10
38/38 [==============================] - 4s 115ms/step - loss: 9071162.0000
Epoch 8/10
38/38 [==============================] - 4s 115ms/step - loss: 9060507.0000
Epoch 9/10
38/38 [==============================] - 4s 115ms/step - loss: 9050109.0000
Epoch 10/10
38/38 [==============================] - 4s 116ms/step - loss: 9039626.0000


SAVE THE MODEL

In [33]:
model.save("Assignment5.h5")